print("    **       ** ")
print("  **  **   **  **")
print("**      ****     **")
print("**     HERYANI   **")
print("  **             **")
print("    **         **")
print("      **     **")
print("        ** **")
print("          **")
